### ISSUE TITLE
Webhook timeout crashes the app

### ISSUE THREAD

**Issue by juansalvatella** [jambonz/jambonz-feature-server#199]
We have been facing some issues with the feature-server on production. Sometimes this is caused by an issue with our webhooks that are not replying in time (i.e. a bot gets stuck trying to get an answer because an external system is not available). The feature-server crashes if the webhook does not reply inside the expected time:

```
{"level":50,"time":1671194932709,"pid":1,"hostname":"feature-server-67bdc8464d-x5j7z","callId":"c3c9e5b0-f7e2-123b-eb8e-42010a9c0034","callSid":"c7e038d0-74a1-45cf-9f51-5eb35c9f86e3","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"646580703","calledNumber":"34910053723","traceId":"eb08ae3ce8ab673f47147489ca1926cb","err":{"type":"HeadersTimeoutError","message":"Headers Timeout Error","stack":"HeadersTimeoutError: Headers Timeout Error\n    at Timeout.onParserTimeout [as _onTimeout] (/opt/app/node_modules/undici/lib/client.js:894:28)\n    at listOnTimeout (node:internal/timers:566:11)\n    at process.processTimers (node:internal/timers:507:7)","name":"HeadersTimeoutError","code":"UND_ERR_HEADERS_TIMEOUT"},"baseUrl":"http://bot-router.apps/","url":"http://bot-router.apps/jambonz-status","msg":"web callback returned unexpected error"}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

HeadersTimeoutError: Headers Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (/opt/app/node_modules/undici/lib/client.js:894:28)
    at listOnTimeout (node:internal/timers:566:11)
    at process.processTimers (node:internal/timers:507:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}
```

I have created a [repo](https://github.com/booklinebot/jambonz-sample-app) with a sample app to troubleshoot issues like this one with a Docker image that can be pulled from Github's registry.

You can use this image to recreate the problem:

`docker run -p 5000:5000 ghcr.io/booklinebot/jambonz-sample-app:master`

Please, let me know if you need anything else.

**Comment by davehorton** [comment]
do I need to use any path when calling the call hook and call webhook of that image?

**Comment by davehorton** [comment]
hmm...this does not crash for me.  I am testing on 0.7.7-20

```
9|jambonz-feature-server  | {"level":20,"time":1671286118263,"pid":473933,"hostname":"ip-10-0-146-18","callId":"24d5ca12-f8b7-123b-3a97-06c6b55f2f3a","callSid":"ac420aad-0e3b-477f-88ee-942eca8cab23","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+15083084809","calledNumber":"+19782978264","traceId":"7d06073a80c8a180d6c59a560a2a32b8","url":"https://public-apps.dev.bookline.io/hello","absUrl":"https://public-apps.dev.bookline.io/hello","hdrs":{"Jambonz-Signature":"t=1671286118,v1=42a170c2d2ccaef98585cc729ae7702454a89b8fc0a6c8cca5d3542c2495e21b","b3":"7d06073a80c8a180d6c59a560a2a32b8-dde6f8bb3db66cb6-1","Content-Type":"application/json"},"msg":"send webhook"}




9|jambonz-feature-server  | {"level":50,"time":1671286148426,"pid":473933,"hostname":"ip-10-0-146-18","callId":"24d5ca12-f8b7-123b-3a97-06c6b55f2f3a","callSid":"ac420aad-0e3b-477f-88ee-942eca8cab23","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+15083084809","calledNumber":"+19782978264","traceId":"7d06073a80c8a180d6c59a560a2a32b8","err":{"type":"HeadersTimeoutError","message":"Headers Timeout Error","stack":"HeadersTimeoutError: Headers Timeout Error\n    at Timeout.onParserTimeout [as _onTimeout] (/home/admin/apps/jambonz-feature-server/node_modules/undici/lib/client.js:894:28)\n    at listOnTimeout (node:internal/timers:566:11)\n    at process.processTimers (node:internal/timers:507:7)","name":"HeadersTimeoutError","code":"UND_ERR_HEADERS_TIMEOUT"},"baseUrl":"https://public-apps.dev.bookline.io","url":"https://public-apps.dev.bookline.io/hello","msg":"web callback returned unexpected error"}
9|jambonz-feature-server  | {"level":30,"time":1671286148427,"pid":473933,"hostname":"ip-10-0-146-18","callId":"24d5ca12-f8b7-123b-3a97-06c6b55f2f3a","callSid":"ac420aad-0e3b-477f-88ee-942eca8cab23","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+15083084809","calledNumber":"+19782978264","traceId":"7d06073a80c8a180d6c59a560a2a32b8","err":{"type":"HeadersTimeoutError","message":"Headers Timeout Error","stack":"HeadersTimeoutError: Headers Timeout Error\n    at Timeout.onParserTimeout [as _onTimeout] (/home/admin/apps/jambonz-feature-server/node_modules/undici/lib/client.js:894:28)\n    at listOnTimeout (node:internal/timers:566:11)\n    at process.processTimers (node:internal/timers:507:7)","name":"HeadersTimeoutError","code":"UND_ERR_HEADERS_TIMEOUT"},"msg":"Error retrieving or parsing application: Headers Timeout Error"}
```

**Comment by juansalvatella** [comment]
I'm using the docker jambonz image for 0.7.7-20.

I’ve registered number 100 to a Carrier using my laptop’s public IP so that Jambonz does the matching and accepts the call. I have configured number 100 with an app that has a random delay of 30s (https://public-apps.dev.bookline.io/hello) to simulate intermittent issues.

If I launch multiple calls to that number with:

`docker run --rm -ti --name sipp_uac --net=host drachtio/sipp sipp -sn uac <jambonz_public_ip> -l 50 -s 100`

After a few seconds the app crashes:

```
{"level":50,"time":1671466716204,"pid":1,"hostname":"feature-server-69dc595c5d-lfsjn","callId":"8f871606-fa5b-123b-56b5-42010a9c0fe4","callSid":"55b58f28-2066-45be-b846-ce338349b805","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"sipp","calledNumber":"100","traceId":"fdb1f248dc3d89954017c4c38a310a2c","err":{"type":"HeadersTimeoutError","message":"Headers Timeout Error","stack":"HeadersTimeoutError: Headers Timeout Error\n    at Timeout.onParserTimeout [as _onTimeout] (/opt/app/node_modules/undici/lib/client.js:902:28)\n    at listOnTimeout (node:internal/timers:566:11)\n    at process.processTimers (node:internal/timers:507:7)","name":"HeadersTimeoutError","code":"UND_ERR_HEADERS_TIMEOUT"},"baseUrl":"https://public-apps.dev.bookline.io/","url":"https://public-apps.dev.bookline.io/hello","msg":"web callback returned unexpected error"}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

HeadersTimeoutError: Headers Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (/opt/app/node_modules/undici/lib/client.js:902:28)
    at listOnTimeout (node:internal/timers:566:11)
    at process.processTimers (node:internal/timers:507:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}

Node.js v18.12.1
```

What logs would be interesting to see?

**Comment by davehorton** [comment]
I think the entire jambonz-feature-server log for the system under test, filtered for the callId or callSid that is for the call that crashed.

Also, is it possible to recreate with something 2 simultaneous calls?

**Comment by davehorton** [comment]
are you still experiencing this @juansalvatella ?

**Comment by davehorton** [comment]
closed for lack of response
