### ISSUE TITLE
Teams target not supported on POST /v1/Accounts/{accountId}/Calls

### ISSUE THREAD

**Issue by ajukes** [jambonz/jambonz-feature-server#23]
When the "to" field is a Teams object and error is thrown

```
1|jambonz-api-server  | {"level":30, "time": "2020-09-30T09:39:57.285Z","pid":10277,"hostname":"ip-172-31-22-10","msg":"invalid client request","stack":"Error: missing or invalid to property: {\"type\":\"teams\",\"number\":\"+441273652002\",\"tenant\":\"5f51637ce390c45fbc95ace6.customers.viva-eu.net\",\"vmail\":false}\n    at validateTo (/home/admin/apps/jambonz-api-server/lib/routes/api/accounts.js:78:9)\n    at validateCreateCall (/home/admin/apps/jambonz-api-server/lib/routes/api/accounts.js:88:3)\n    at router.post (/home/admin/apps/jambonz-api-server/lib/routes/api/accounts.js:276:11)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","type":"Error","v":1}
```

**Comment by davehorton** [comment]
This was actually a bug in jambonz-api-server and has been fixed in [this commit](https://github.com/jambonz/jambonz-api-server/commit/53763aae145b5cd8d90917c6994a6da6645070f6)
