### ISSUE TITLE
ClientDestroyedError when using Create Call API

### ISSUE THREAD

**Issue by vcidst** [jambonz/jambonz-feature-server#266]
I'm seeing this error whenever the Jambonz Create Call API is used. This is happening with the tag version `0.7.11`

```
ClientDestroyedError: The client is destroyed
    at Client.dispatch (/opt/app/node_modules/undici/lib/dispatcher-base.js:171:15)
    at Client.request (/opt/app/node_modules/undici/lib/api/api-request.js:193:10)
    at /opt/app/node_modules/undici/lib/api/api-request.js:186:15
    at new Promise (<anonymous>)
    at Client.request (/opt/app/node_modules/undici/lib/api/api-request.js:185:12)
    at HttpRequestor.request (/opt/app/lib/utils/http-requestor.js:124:57)
    at RestCallSession._notifyCallStatusChange (/opt/app/lib/session/call-session.js:1614:21)
    at RestCallSession.emit (node:events:513:28)
    at RestCallSession.emit (node:domain:489:12)
    at /opt/app/lib/http-routes/api/create-call.js:228:20 {
```

**Comment by davehorton** [comment]
could you include a full log?
