### ISSUE TITLE
final status not sent if recording is on and call ended by jambonz

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-feature-server#412]
To recreate: enable call recording on your account, make a call to 'hello-world' and wait to let jambonz hangup the call after saying the message.
```

3|jambonz-feature-server  | {"level":30,"time":1690993228390,"pid":153102,"hostname":"ip-172-20-10-69","callId":"4c7e596b-abf3-123c-9193-0e9252b57157","callSid":"82cc2aad-62b1-48e6-987c-f8fe909bf03d","accountSid":"55c0b573-da3e-4977-b568-fb546270f500","callingNumber":"+15083084809","calledNumber":"+17742529066","traceId":"e5aac5230bf7853752f80b793084acd3","msg":"CallSession:exec completed task #0:2: say"}
3|jambonz-feature-server  | {"level":30,"time":1690993228390,"pid":153102,"hostname":"ip-172-20-10-69","callId":"4c7e596b-abf3-123c-9193-0e9252b57157","callSid":"82cc2aad-62b1-48e6-987c-f8fe909bf03d","accountSid":"55c0b573-da3e-4977-b568-fb546270f500","callingNumber":"+15083084809","calledNumber":"+17742529066","traceId":"e5aac5230bf7853752f80b793084acd3","msg":"CallSession:exec all tasks complete"}
3|jambonz-feature-server  | {"level":30,"time":1690993228392,"pid":153102,"hostname":"ip-172-20-10-69","msg":"SessionTracker:remove callSid 82cc2aad-62b1-48e6-987c-f8fe909bf03d, we have 0 being tracked"}
3|jambonz-feature-server  | {"level":50,"time":1690993228393,"pid":153102,"hostname":"ip-172-20-10-69","callId":"4c7e596b-abf3-123c-9193-0e9252b57157","callSid":"82cc2aad-62b1-48e6-987c-f8fe909bf03d","accountSid":"55c0b573-da3e-4977-b568-fb546270f500","callingNumber":"+15083084809","calledNumber":"+17742529066","traceId":"e5aac5230bf7853752f80b793084acd3","err":{"type":"ClientClosedError","message":"The client is closed","stack":"ClientClosedError: The client is closed\n    at Client.dispatch (/home/admin/apps/jambonz-feature-server/node_modules/undici/lib/dispatcher-base.js:176:15)\n    at Client.request (/home/admin/apps/jambonz-feature-server/node_modules/undici/lib/api/api-request.js:170:10)\n    at /home/admin/apps/jambonz-feature-server/node_modules/undici/lib/api/api-request.js:163:15\n    at new Promise (<anonymous>)\n    at Client.request (/home/admin/apps/jambonz-feature-server/node_modules/undici/lib/api/api-request.js:162:12)\n    at HttpRequestor.request (/home/admin/apps/jambonz-feature-server/lib/utils/http-requestor.js:142:57)\n    at InboundCallSession.executeStatusCallback (/home/admin/apps/jambonz-feature-server/lib/session/call-session.js:1804:27)\n    at InboundCallSession._notifyCallStatusChange (/home/admin/apps/jambonz-feature-server/lib/session/call-session.js:1790:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","name":"ClientClosedError","code":"UND_ERR_CLOSED"},"baseUrl":"https://public-apps.jambonz.cloud","url":"https://public-apps.jambonz.cloud/call-status","msg":"web callback returned unexpected error"}
3|jambonz-feature-server  | {"level":30,"time":1690993228394,"pid":153102,"hostname":"ip-172-20-10-69","callId":"4c7e596b-abf3-123c-9193-0e9252b57157","callSid":"82cc2aad-62b1-48e6-987c-f8fe909bf03d","accountSid":"55c0b573-da3e-4977-b568-fb546270f500","callingNumber":"+15083084809","calledNumber":"+17742529066","traceId":"e5aac5230bf7853752f80b793084acd3","err":{"type":"ClientClosedError","message":"The client is closed","stack":"ClientClosedError: The client is closed\n    at Client.dispatch (/home/admin/apps/jambonz-feature-server/node_modules/undici/lib/dispatcher-base.js:176:15)\n    at Client.request (/home/admin/apps/jambonz-feature-server/node_modules/undici/lib/api/api-request.js:170:10)\n    at /home/admin/apps/jambonz-feature-server/node_modules/undici/lib/api/api-request.js:163:15\n    at new Promise (<anonymous>)\n    at Client.request (/home/admin/apps/jambonz-feature-server/node_modules/undici/lib/api/api-request.js:162:12)\n    at HttpRequestor.request (/home/admin/apps/jambonz-feature-server/lib/utils/http-requestor.js:142:57)\n    at InboundCallSession.executeStatusCallback (/home/admin/apps/jambonz-feature-server/lib/session/call-session.js:1804:27)\n    at InboundCallSession._notifyCallStatusChange (/home/admin/apps/jambonz-feature-server/lib/session/call-session.js:1790:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","name":"ClientClosedError","code":"UND_ERR_CLOSED"},"msg":"CallSession:_notifyCallStatusChange error sending completed undefined"}
3|jambonz-feature-server  | {"level":30,"time":1690993228433,"pid":153102,"hostname":"ip-172-20-10-69","callId":"4c7e596b-abf3-123c-9193-0e9252b57157","callSid":"82cc2aad-62b1-48e6-987c-f8fe909bf03d","accountSid":"55c0b573-da3e-4977-b568-fb546270f500","callingNumber":"+15083084809","calledNumber":"+17742529066","traceId":"e5aac5230bf7853752f80b793084acd3","msg":"CallSession:startBackgroundListen: listen completed"}
```

**Comment by davehorton** [comment]
fixed
