### ISSUE TITLE
nvidia not working in dial transcribe 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#564]
2|savgw-feature-server  | {"level":30,"time":1702477911965,"pid":1706783,"hostname":"ip-172-23-11-191","callId":"25c82481-1467-123d-4588-0af22a2005c7","callSid":"b0c202f7-9c1e-4365-89ff-6503f121eb5d","accountSid":"5c08914e-c863-4d11-aeb0-b7577c2552f6","callingNumber":"+18448735673","calledNumber":"+16628835965","traceId":"769ed34f01a0d3dfc2d34b5f1278e0d5","msg":"CallSession:exec completed task #1:1: say"}
2|savgw-feature-server  | {"level":30,"time":1702477911965,"pid":1706783,"hostname":"ip-172-23-11-191","callId":"25c82481-1467-123d-4588-0af22a2005c7","callSid":"b0c202f7-9c1e-4365-89ff-6503f121eb5d","accountSid":"5c08914e-c863-4d11-aeb0-b7577c2552f6","callingNumber":"+18448735673","calledNumber":"+16628835965","traceId":"769ed34f01a0d3dfc2d34b5f1278e0d5","msg":"CallSession:exec starting task #1:2: dial"}
2|savgw-feature-server  | {"level":30,"time":1702477913513,"pid":1706783,"hostname":"ip-172-23-11-191","callSid":"effa1ce0-9116-4e19-bd3f-435e237fdf59","parentCallSid":"b0c202f7-9c1e-4365-89ff-6503f121eb5d","callId":"32af3056-1467-123d-c2bb-0ebc875ec8e1","tasks":"[]","msg":"CallSession:exec starting 0 tasks"}
2|savgw-feature-server  | Error: No speech-to-text service credentials for nvidia_stt have been configured
2|savgw-feature-server  |     at TaskTranscribe._initSpeechCredentials (/home/admin/apps/savgw-feature-server/lib/tasks/stt-task.js:73:13)
2|savgw-feature-server  |     at TaskTranscribe.exec (/home/admin/apps/savgw-feature-server/lib/tasks/transcribe.js:104:42)
2|savgw-feature-server  |     at TaskDial._selectSingleDial (/home/admin/apps/savgw-feature-server/lib/tasks/dial.js:762:50)
2|savgw-feature-server  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2|savgw-feature-server  |     at async TaskDial._connectSingleDial (/home/admin/apps/savgw-feature-server/lib/tasks/dial.js:675:5)
2|savgw-feature-server  |     at async SingleDialer.<anonymous> (/home/admin/apps/savgw-feature-server/lib/tasks/dial.js:627:15)
2|savgw-feature-server  | {"level":30,"time":1702477913513,"pid":1706783,"hostname":"ip-172-23-11-191","callSid":"effa1ce0-9116-4e19-bd3f-435e237fdf59","parentCallSid":"b0c202f7-9c1e-4365-89ff-6503f121eb5d","callId":"32af3056-1467-123d-c2bb-0ebc875ec8e1","msg":"CallSession:exec all tasks complete"}
2|savgw-feature-server  | {"level":30,"time":1702477913514,"pid":1706783,"hostname":"ip-172-23-11-191","msg":"SessionTracker:add callSid effa1ce0-9116-4e19-bd3f-435e237fdf59, we have 2 session being tracked"}
2|savgw-feature-server  | {"level":30,"time":1702477913515,"pid":1706783,"hostname":"ip-172-23-11-191","callId":"25c82481-1467-123d-4588-0af22a2005c7","callSid":"b0c202f7-9c1e-4365-89ff-6503f121eb5d","accountSid":"5c08914e-c863-4d11-aeb0-b7577c2552f6","callingNumber":"+18448735673","calledNumber":"+16628835965","traceId":"769ed34f01a0d3dfc2d34b5f1278e0d5","msg":"ERROR stt using nvidia_stt requested but creds not supplied"}

**Comment by vdharashive** [comment]
this issue also notice for nunace and custom engines as well

**Comment by vdharashive** [comment]
Nuance and riva its working
