### ISSUE TITLE
Bug : TypeError: this.data.recognizer.altLanguages.concat is not a function

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#565]
3|jambonz-feature-server|{
  "level": 20,
  "time": 1702557638972,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "command": "redirect",
  "call_sid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "queueCommand": false,
  "data": [
    {
      "verb": "config",
      "synthesizer": {
        "vendor": "microsoft",
        "voice": "en-AU-NatashaNeural",
        "language": "en-AU"
      },
      "recognizer": {
        "vendor": "microsoft",
        "language": "en-AU",
        "altLanguages": [
          "ar-LB",
          "en-AU",
          "es-ES"
        ]
      }
    },
    {
      "verb": "tag",
      "data": {
        "userNoInputCounter": 1,
        "retryCount": 3
      }
    },
    {
      "verb": "sip:request",
      "method": "INFO",
      "headers": {
        "X-AC-Action": "start-siprec;recording-ip-group=\"SIPRec1\""
      }
    },
    {
      "verb": "sip:request",
      "method": "INFO",
      "headers": {
        "X-AC-Action": "start-siprec;recording-ip-group=\"SIPRec2\""
      }
    },
    {
      "verb": "gather",
      "actionHook": "/actions/hooks",
      "input": [
        "digits",
        "speech"
      ],
      "interDigitTimeout": 2,
      "minDigits": 1,
      "finishOnKey": "#",
      "numDigits": 12,
      "say": {
        "text": "You have now reached Multilanguage Bot, Please Specify Intent."
      },
      "bargein": false,
      "listenDuringPrompt": false,
      "timeout": 10,
      "dtmfBargein": false
    }
  ],
  "msg": "received command"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638972,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "command": "redirect",
  "queueCommand": false,
  "data": [
    {
      "verb": "config",
      "synthesizer": {
        "vendor": "microsoft",
        "voice": "en-AU-NatashaNeural",
        "language": "en-AU"
      },
      "recognizer": {
        "vendor": "microsoft",
        "language": "en-AU",
        "altLanguages": [
          "ar-LB",
          "en-AU",
          "es-ES"
        ]
      }
    },
    {
      "verb": "tag",
      "data": {
        "userNoInputCounter": 1,
        "retryCount": 3
      }
    },
    {
      "verb": "sip:request",
      "method": "INFO",
      "headers": {
        "X-AC-Action": "start-siprec;recording-ip-group=\"SIPRec1\""
      }
    },
    {
      "verb": "sip:request",
      "method": "INFO",
      "headers": {
        "X-AC-Action": "start-siprec;recording-ip-group=\"SIPRec2\""
      }
    },
    {
      "verb": "gather",
      "actionHook": "/actions/hooks",
      "input": [
        "digits",
        "speech"
      ],
      "interDigitTimeout": 2,
      "minDigits": 1,
      "finishOnKey": "#",
      "numDigits": 12,
      "say": {
        "text": "You have now reached Multilanguage Bot, Please Specify Intent."
      },
      "bargein": false,
      "listenDuringPrompt": false,
      "timeout": 10,
      "dtmfBargein": false
    }
  ],
  "msg": "CallSession:_onCommand - received command"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638972,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "tasks": "[config{set synthesizer{microsoft,en-AU,en-AU-NatashaNeural},set recognizer{microsoft,en-AU}},tag,sip:request,sip:request,gather{inputs=[speech,digits],vendor=default,language=default,with nested say task}]",
  "msg": "CallSession:_onCommand new task list"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638972,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "tasks": "[config{set synthesizer{microsoft,en-AU,en-AU-NatashaNeural},set recognizer{microsoft,en-AU}},tag,sip:request,sip:request,gather{inputs=[speech,digits],vendor=default,language=default,with nested say task}]",
  "msg": "CallSession:replaceApplication reset with 5 new tasks, stack depth is 1"
}3|jambonz-feature-server|{
  "level": 20,
  "time": 1702557638972,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "gather is being killed"
}3|jambonz-feature-server|{
  "level": 20,
  "time": 1702557638972,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "Gather:_killAudio: killing playback of any audio"
}3|jambonz-feature-server|{
  "level": 20,
  "time": 1702557638973,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "TaskGather:resolve with reason killed"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638973,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "CallSession:exec completed task #0:2: gather"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638973,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "CallSession:exec starting task #1:1: config"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638973,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "synthesizer": {
    "vendor": "microsoft",
    "voice": "en-AU-NatashaNeural",
    "language": "en-AU"
  },
  "msg": "Config: updated synthesizer"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638973,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "altLanguages": [
    "ar-LB",
    "en-AU",
    "es-ES"
  ],
  "msg": "Config: updated altLanguages"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638973,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "recognizer": {
    "vendor": "microsoft",
    "language": "en-AU",
    "altLanguages": [
      "ar-LB",
      "en-AU",
      "es-ES"
    ]
  },
  "isContinuousAsr": false,
  "msg": "Config: updated recognizer"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638973,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "CallSession:exec completed task #1:1: config"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638973,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "CallSession:exec starting task #1:2: tag"
}3|jambonz-feature-server|{
  "level": 20,
  "time": 1702557638973,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "customerData": {
    "userNoInputCounter": 1,
    "retryCount": 3
  },
  "msg": "TaskTag:exec set customer data in callInfo"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638973,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "CallSession:exec completed task #1:2: tag"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638973,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "CallSession:exec starting task #1:3: sip:request"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557638973,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "dlg": {
    "id": "d02272aa-1520-123d-62b6-0eb94b3c8831;from-tag=3H6N91pD6c5SS",
    "type": "uas",
    "sip": {
      "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
      "remoteTag": "3H6N91pD6c5SS",
      "localTag": "aNy05NQ88FHyj"
    },
    "local": {
      "uri": "sip:172.31.10.207:5060",
      "sdp": "v=0\r\no=FreeSWITCH 1702531775 1702531776 IN IP4 172.31.10.207\r\ns=FreeSWITCH\r\nc=IN IP4 172.31.10.207\r\nt=0 0\r\nm=audio 25858 RTP/AVP 0 126\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:126 telephone-event/8000\r\na=fmtp:126 0-15\r\na=ptime:20\r\na=sendrecv\r\na=rtcp-mux\r\na=rtcp:25858 IN IP4 172.31.10.207\r\n",
      "contact": "<sip:172.31.10.207:5060>"
    },
    "remote": {
      "uri": "sip:172.31.10.85:5060",
      "sdp": "v=0\r\no=- 7502075223627034628 2 IN IP4 172.31.10.236\r\ns=-\r\nt=0 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS uDTQtY3TkfdIiMMwWaOeSXKzk5GZHPTGVJs4\r\nm=audio 42520 RTP/AVP 111 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 172.31.10.236\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=msid:uDTQtY3TkfdIiMMwWaOeSXKzk5GZHPTGVJs4 cb933b19-525f-416c-9108-77bdb77995b4\r\na=ssrc:764938188 cname:CP3Elt2bGqvscWb+\r\na=ssrc:764938188 msid:uDTQtY3TkfdIiMMwWaOeSXKzk5GZHPTGVJs4 cb933b19-525f-416c-9108-77bdb77995b4\r\na=mid:0\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtcp-fb:111 transport-cc\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=sendrecv\r\na=rtcp:42521\r\na=rtcp-mux\r\n"
    },
    "onHold": false
  },
  "msg": "TaskSipRequest: sending a SIP INFO"
}3|jambonz-feature-server|{
  "level": 20,
  "time": 1702557639225,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "result": {
    "result": "success",
    "sipStatus": 415
  },
  "msg": "TaskSipRequest: received response to INFO"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557639225,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "CallSession:exec completed task #1:3: sip:request"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557639225,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "CallSession:exec starting task #1:4: sip:request"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557639225,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "dlg": {
    "id": "d02272aa-1520-123d-62b6-0eb94b3c8831;from-tag=3H6N91pD6c5SS",
    "type": "uas",
    "sip": {
      "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
      "remoteTag": "3H6N91pD6c5SS",
      "localTag": "aNy05NQ88FHyj"
    },
    "local": {
      "uri": "sip:172.31.10.207:5060",
      "sdp": "v=0\r\no=FreeSWITCH 1702531775 1702531776 IN IP4 172.31.10.207\r\ns=FreeSWITCH\r\nc=IN IP4 172.31.10.207\r\nt=0 0\r\nm=audio 25858 RTP/AVP 0 126\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:126 telephone-event/8000\r\na=fmtp:126 0-15\r\na=ptime:20\r\na=sendrecv\r\na=rtcp-mux\r\na=rtcp:25858 IN IP4 172.31.10.207\r\n",
      "contact": "<sip:172.31.10.207:5060>"
    },
    "remote": {
      "uri": "sip:172.31.10.85:5060",
      "sdp": "v=0\r\no=- 7502075223627034628 2 IN IP4 172.31.10.236\r\ns=-\r\nt=0 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS uDTQtY3TkfdIiMMwWaOeSXKzk5GZHPTGVJs4\r\nm=audio 42520 RTP/AVP 111 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 172.31.10.236\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=msid:uDTQtY3TkfdIiMMwWaOeSXKzk5GZHPTGVJs4 cb933b19-525f-416c-9108-77bdb77995b4\r\na=ssrc:764938188 cname:CP3Elt2bGqvscWb+\r\na=ssrc:764938188 msid:uDTQtY3TkfdIiMMwWaOeSXKzk5GZHPTGVJs4 cb933b19-525f-416c-9108-77bdb77995b4\r\na=mid:0\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtcp-fb:111 transport-cc\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=sendrecv\r\na=rtcp:42521\r\na=rtcp-mux\r\n"
    },
    "onHold": false
  },
  "msg": "TaskSipRequest: sending a SIP INFO"
}3|jambonz-feature-server|{
  "level": 20,
  "time": 1702557639474,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "result": {
    "result": "success",
    "sipStatus": 415
  },
  "msg": "TaskSipRequest: received response to INFO"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557639474,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "CallSession:exec completed task #1:4: sip:request"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557639474,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "CallSession:exec starting task #1:5: gather"
}3|jambonz-feature-server|{
  "level": 20,
  "time": 1702557639474,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "options": {
    "actionHook": "/actions/hooks",
    "input": [
      "digits",
      "speech"
    ],
    "interDigitTimeout": 2,
    "minDigits": 1,
    "finishOnKey": "#",
    "numDigits": 12,
    "say": {
      "text": "You have now reached Multilanguage Bot, Please Specify Intent."
    },
    "bargein": false,
    "listenDuringPrompt": false,
    "timeout": 10,
    "dtmfBargein": false,
    "recognizer": {
      "hints": [
        
      ],
      "altLanguages": [
        
      ]
    }
  },
  "msg": "Gather:exec"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557639474,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "Speech vendor: microsoft  selected"
}3|jambonz-feature-server|{
  "level": 50,
  "time": 1702557639474,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "err": {
    "type": "TypeError",
    "message": "this.data.recognizer.altLanguages.concat is not a function",
    "stack": "TypeError: this.data.recognizer.altLanguages.concat is not a function\n    at TaskGather.exec (/home/admin/apps/jambonz-feature-server/lib/tasks/gather.js:120:77)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InboundCallSession.exec (/home/admin/apps/jambonz-feature-server/lib/session/call-session.js:923:11)"
  },
  "msg": "Error executing task  #1:5: gather"
}3|jambonz-feature-server|{
  "level": 30,
  "time": 1702557639474,
  "pid": 57025,
  "hostname": "ip-172-31-10-207",
  "callId": "d02272aa-1520-123d-62b6-0eb94b3c8831",
  "callSid": "e258d280-6d2f-41b0-b2f5-07ba0a6c31f9",
  "accountSid": "3978e7ef-e014-4a9e-9184-ff24a19d9fad",
  "callingNumber": "u-c07f803d-742e-5b51-b1b0-fbf37d79f4e1",
  "calledNumber": "st-1f1fcbde-d7bc-581b-abb6-a09101586e8e",
  "traceId": "ee9199ed6929c5086c6c5fd7f8796ffa",
  "msg": "CallSession:exec all tasks complete"
}

**Comment by vdharashive** [comment]
on setting altLanguages error is comming, there has to be option to remove altLanguages which was set for session , 

this bug started after having config with recognize option

**Comment by vdharashive** [comment]
Fixied

**Comment by vdharashive** [comment]
@xquanluu this issue still remains , we have pull the latest release
