### ISSUE TITLE
Redirecting call while on hold leaves call without media

### ISSUE THREAD

**Issue by avoylenko** [jambonz/jambonz-feature-server#577]
The scenario is below: 
1. Bridge parties with dial verb
2. Put a call on hold on B-side
3. Redirect the call to another application

As result the call left without media.

ReInvite for hold:

`
9|jambonz-feature-server  | {"level":30,"time":1703284700682,"pid":115370,"hostname":"ip-10-0-150-157","callSid":"0ffd14b8-6654-4738-809a-ea22067f1abd","parentCallSid":"5292c890-3e23-4e51-b128-7c4b7f47549e","callId":"a2273a44-1bbd-123d-3ebe-06d9a3589499","offer":"v=0\r\no=- 4590788354136074957 3 IN IP4 10.0.150.157\r\ns=-\r\nt=0 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS 6ed29443-0db8-43da-b817-47ff8bd21d03\r\nm=audio 58668 RTP/AVP 0 8 102 9 101 103 13\r\nc=IN IP4 10.0.150.157\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=msid:6ed29443-0db8-43da-b817-47ff8bd21d03 251c4711-9f28-42cd-b21d-6cd6a40e0aeb\r\na=ssrc:216971130 cname:oSc0BdMDF7d4PdhC\r\na=ssrc:216971130 msid:6ed29443-0db8-43da-b817-47ff8bd21d03 251c4711-9f28-42cd-b21d-6cd6a40e0aeb\r\na=mid:1\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:102 opus/48000/2\r\na=fmtp:102 minptime=10;useinbandfec=1\r\na=rtpmap:9 G722/8000\r\na=rtpmap:101 telephone-event/8000\r\na=rtpmap:103 telephone-event/48000\r\na=rtpmap:13 CN/8000\r\na=sendonly\r\na=rtcp:58669\r\na=ptime:20\r\n","answer":"v=0\r\no=Jambonz-Mediaserver 1703257951 1703257953 IN IP4 10.0.150.157\r\ns=Jambonz-Mediaserver\r\nc=IN IP4 10.0.150.157\r\nt=0 0\r\nm=audio 26742 RTP/AVP 0 101 103\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-16\r\na=rtpmap:103 telephone-event/48000\r\na=fmtp:103 0-16\r\na=recvonly\r\na=ptime:20\r\n","msg":"SingleDialer:exec: handling reINVITE"}
`

New instructions from the webhook on redirect:
`
9|jambonz-feature-server  | {"level":30,"time":1703284707953,"pid":115370,"hostname":"ip-10-0-150-157","callId":"9a7c5a98-1bbd-123d-76a1-06d9a3589499","callSid":"5292c890-3e23-4e51-b128-7c4b7f47549e","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"7006","calledNumber":"6666","traceId":"c6ac0ef73ab23a98746ebb108100ef9f","response":[{"verb":"play","url":"silence_stream://500","earlyMedia":false,"loop":1},{"verb":"tag","data":{"action":"hold","conversationId":43,"isClient":true,"inqueue":true,"record":true}},{"verb":"enqueue","name":"hold","waitHook":"/hold-music"}],"msg":"HttpRequestor:request POST /hold succeeded in 299ms"}
`

I see the below error message in the log:
`
9|jambonz-feature-server  | {"level":30,"time":1703284708121,"pid":115370,"hostname":"ip-10-0-150-157","callId":"9a7c5a98-1bbd-123d-76a1-06d9a3589499","callSid":"5292c890-3e23-4e51-b128-7c4b7f47549e","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"7006","calledNumber":"6666","traceId":"c6ac0ef73ab23a98746ebb108100ef9f","err":{"type":"Error","message":"endpoint no longer active","stack":"Error: endpoint no longer active\n    at __x (/home/admin/apps/jambonz-feature-server/node_modules/drachtio-fsmrf/lib/endpoint.js:1148:40)\n    at /home/admin/apps/jambonz-feature-server/node_modules/drachtio-fsmrf/lib/endpoint.js:1161:7\n    at new Promise (<anonymous>)\n    at Endpoint.execute (/home/admin/apps/jambonz-feature-server/node_modules/drachtio-fsmrf/lib/endpoint.js:1160:12)\n    at __x (/home/admin/apps/jambonz-feature-server/node_modules/drachtio-fsmrf/lib/endpoint.js:317:32)\n    at /home/admin/apps/jambonz-feature-server/node_modules/drachtio-fsmrf/lib/endpoint.js:334:7\n    at new Promise (<anonymous>)\n    at Endpoint.play (/home/admin/apps/jambonz-feature-server/node_modules/drachtio-fsmrf/lib/endpoint.js:333:12)\n    at /home/admin/apps/jambonz-feature-server/lib/tasks/enqueue.js:163:22\n    at new Promise (<anonymous>)"},"msg":"TaskEnqueue:_doWait: failed retrieving waitHook for queue:9351f46a-678c-43f5-b8a6-d4eb58d131af:hold"}
`

**Comment by xquanluu** [comment]
Hi @avoylenko 
is this issue also happened if B leg is not onhold?

**Comment by avoylenko** [comment]
@xquanluu nope, only when B-leg is on hold

**Comment by xquanluu** [comment]
then the PR is not good, there is some other place to handle anchor-media, but missing a case when B-leg is onhold. I'm checking on my end, please wait

**Comment by xquanluu** [comment]
Hi Hi @avoylenko I cannot reproduce the issue on my jambonz.me please help to let me know if this application can reproduce the issue

`const service = ({ logger, client, makeService }) => {
  const svc = makeService({ path: "/conference" });

  svc.on("session:new", (session) => {
    session.locals = { logger: logger.child({ call_sid: session.call_sid }) };
    logger.info({ session }, `new incoming call: ${session.call_sid}`);

    session
      .on("close", onClose.bind(null, session))
      .on("error", onError.bind(null, session));

    // Put incoming call to dial verb
    session
      .pause({ length: 1.5 })
      .say({ text: welcomeText })
      .dial({
        callerId: "+16173331212",
        answerOnBridge: true,
        target: [
          {
            type: "user",
            name: "xhoaluu2@sip.jambonz.me",
          },
        ],
      })
      .send();

    // kill dial and say the text
    setTimeout(() => {
      session
      .say({ text: welcomeText })
      .send();
    }, 15_000);
  });
  };`

**Comment by avoylenko** [comment]
@xquanluu as I see in your case JBZ server is controlled by websocket connection, in my case application is webhook based. If you want I can share the verb instructions with you, but they are simple. Dial the phone, hold the line, user LLC to redirect the call.

**Comment by xquanluu** [comment]
Hi @avoylenko Please if there is jambonz-node-client app, please help to zip it, attach it here then I can test.

I think the difference in ws hook or http hook should not be a problem they are the same in the way we control media

**Comment by avoylenko** [comment]
@xquanluu the flow is the next:

We receiving inbound call and running the below verbs:

```
[
    {
        "verb": "play",
        "url": "silence_stream://500",
        "earlyMedia": false,
        "loop": 1
    },
    {
        "verb": "config",
        "listen": {
            "wsAuth": {
                "username": "record",
                "password": "record"
            },
            "enable": true,
            "sampleRate": 8000,
            "mixType": "stereo",
            "url": "http://127.0.0.1:3002/record/s3_compatible"
        }
    },
    {
        "verb": "config",
        "sipRequestWithinDialogHook": "/indialog-hook"
    },
    {
        "verb": "tag",
        "data": {
            "action": "agent",
            "conversationId": 43,
            "isClient": true,
            "inqueue": true,
            "record": true
        }
    },
    {
        "verb": "dial",
        "target": [
            {
                "type": "user",
                "name": "1000"
            }
        ],
        "answerOnBridge": true,
        "callerName": "voice-7006",
        "actionHook": "/dial-agent-action",
        "confirmHook": "/dial-agent-confirm?conversationId=43",
        "dialMusic": "https://cdn.freesound.org/previews/39/39061_402511-lq.mp3",
        "referHook": "/refer-hook",
        "anchorMedia": false
    }
]



[
    {
        "verb": "play",
        "url": "silence_stream://500",
        "earlyMedia": false,
        "loop": 1
    },
    {
        "verb": "tag",
        "data": {
            "action": "hold",
            "conversationId": 43,
            "isClient": true,
            "inqueue": true,
            "record": true
        }
    },
    {
        "verb": "enqueue",
        "name": "hold",
        "waitHook": "/hold-music"
    }
]
```

Agent (phone number 1000) places the call on hold and during the hold JBZ received the next API request from NODE-RED server:

`25 Dec 10:41:47 - [info] [lcc:redirect to hold] invoking LCC with payload {"call_hook":{"url":"/hold"}} at http://aws.jambonz.demo.novait.com.ua/api/v1/Accounts/9351f46a-678c-43f5-b8a6-d4eb58d131af/Calls/ec172c9f-fcfd-40cf-8ca6-599bc521a065
`

```
[
    {
        "verb": "play",
        "url": "silence_stream://500",
        "earlyMedia": false,
        "loop": 1
    },
    {
        "verb": "tag",
        "data": {
            "action": "hold",
            "conversationId": 43,
            "isClient": true,
            "inqueue": true,
            "record": true
        }
    },
    {
        "verb": "enqueue",
        "name": "hold",
        "waitHook": "/hold-music"
    }
]

```

**Comment by xquanluu** [comment]
Hi @avoylenko I'm still not be able to reproduce the issue, I'm using bellow code for http client instead of ws.

1/ connect 2 legs via dial verb,
2/ put B leg onhold
3/ LCC to move caller leg to say verb

```
const router = require('express').Router();
const WebhookResponse = require('@jambonz/node-client').WebhookResponse;

router.post('/', (req, res) => {
  const {logger, client} = req.app.locals;
  logger.error({payload: req.body}, 'POST /dial-time');
  try {
    const app = new WebhookResponse();
    app.dial({
      answerOnBridge: true,
      target: [
        {
          type: 'user',
          name: 'xhoaluu2@sip.jambonz.me'
        }
      ]
    });
    setTimeout(async() => {
      const a = await client.calls.update(req.body.call_sid, {
        call_hook: 'https://abe8-2001-ee0-d744-b7f0-9066-1762-ef79-7316.ngrok-free.app/dial-time/say'
      });
      logger.error({a}, 'Update call');
    }, 10000);
    res.status(200).json(app);
  } catch (err) {
    logger.error({err}, 'Error');
    res.sendStatus(503);
  }
});

router.post('/say', (req, res) => {
  const {logger} = req.app.locals;
  logger.error({payload: req.body}, 'POST /dial-time/say');
  try {
    const app = new WebhookResponse();
    app.say({
      text: 'Hello How are you, We are really good and you'
    });
    res.status(200).json(app);
  } catch (err) {
    logger.error({err}, 'Error');
    res.sendStatus(503);
  }
});

module.exports = router;

```

**Comment by xquanluu** [comment]
Can you please share a complete log from your site?

**Comment by avoylenko** [comment]
I prepare a simple application to reproduce the issue. You can get it from https://github.com/avoylenko/jbz-hold-redirect-issue. You just need to put a call on hold on called party(B-leg) and await 10 secs until the calling party will be redirected into the queue with waithook enabled.  As result the waithook music would be played. It's strange that i my case there are no audio at all. Gonna investigate this further

**Comment by avoylenko** [comment]
The session was not anchored on FS. Closing
