### ISSUE TITLE
relative url for listen does not work if createCall REST supplied call_hook

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-feature-server#6]
When a user creates a call through REST, and supplies a 'call_hook' property rather than 'application_sid', a listen verb that uses a relative url fails with the following error

```
{"level":20,"time":1580832859316,"pid":15381,"hostname":"ip-172-31-3-33","callId":"3be80dce-c20c-1238-6185-06d91d68c9b0","callSid":"3b7607ec-12e9-4c36-b582-e816593ca14b","action":"/ivr/973e4b02-bc61-4fc0-8cdb-3ce4fa4df8d1","callerId":"447956697540","dialMusic":"https://vibe-public.s3-eu-west-1.amazonaws.com/en-gb.wav","timeLimit":14400,"timeout":30,"answerOnBridge":true,"target":[{"type":"user","name":"ajukes"},{"type":"user","name":"daveh"},{"type":"user","name":"brandon"}],"listen":{"url":"/record","mixType":"stereo","finishOnKey":"#","maxLength":14400,"metadata":{"customerId":null,"parentCallSid":"3b7607ec-12e9-4c36-b582-e816593ca14b"},"passDtmf":true,"playBeep":false,"sampleRate":8000},"msg":"makeTask: dial","v":1}
2|jambonz-feature-server  | {"level":20,"time":1580832859317,"pid":15381,"hostname":"ip-172-31-3-33","callId":"3be80dce-c20c-1238-6185-06d91d68c9b0","callSid":"3b7607ec-12e9-4c36-b582-e816593ca14b","url":"/record","mixType":"stereo","finishOnKey":"#","maxLength":14400,"metadata":{"customerId":null,"parentCallSid":"3b7607ec-12e9-4c36-b582-e816593ca14b"},"passDtmf":true,"playBeep":false,"sampleRate":8000,"msg":"makeTask: listen","v":1}
2|jambonz-feature-server  | TypeError: Cannot read property 'originalRequest' of undefined
2|jambonz-feature-server  |     at TaskListen.normalizeUrl (/home/deploy/jambonz-feature-server/lib/tasks/task.js:64:35)
2|jambonz-feature-server  |     at new TaskListen (/home/deploy/jambonz-feature-server/lib/tasks/listen.js:19:22)
2|jambonz-feature-server  |     at makeTask (/home/deploy/jambonz-feature-server/lib/tasks/make_task.js:41:14)
2|jambonz-feature-server  |     at new TaskDial (/home/deploy/jambonz-feature-server/lib/tasks/dial.js:59:25)
2|jambonz-feature-server  |     at makeTask (/home/deploy/jambonz-feature-server/lib/tasks/make_task.js:23:14)
2|jambonz-feature-server  |     at normalizeJamones.map (/home/deploy/jambonz-feature-server/lib/utils/retrieve-app.js:28:56)
2|jambonz-feature-server  |     at Array.map (<anonymous>)
2|jambonz-feature-server  |     at retrieveApp (/home/deploy/jambonz-feature-server/lib/utils/retrieve-app.js:28:41)
2|jambonz-feature-server  |     at Request.request [as _callback] (/home/deploy/jambonz-feature-server/lib/utils/notifiers.js:35:26)
2|jambonz-feature-server  |     at Request.self.callback (/home/deploy/jambonz-feature-server/node_modules/request/request.js:185:22)
2|jambonz-feature-server  | 
```

**Comment by davehorton** [comment]
upon review, the bug is different than described above.  The issue is that we try to normalize the url in the task constructor, before the task has been exec'ed within a call session.  Next push should resolve this.

**Comment by davehorton** [comment]
fixed.  please test and close if you concur

**Comment by ajukes** [comment]
Confirmed fixed
