### ISSUE TITLE
Bug : Nuance cloud instance giving error 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#775]
Nunace connecting to cloud is giving below error 

DEBUG [05:59:41.747] (1028738): Gather:exec
    callId: "cd20ec79-9e6c-123d-7d9a-0e2ecbcba261"
    callSid: "8a347f80-8306-40f5-b689-c0a31a5351a0"
    accountSid: "3978e7ef-e014-4a9e-9184-ff24a19d9fad"
    callingNumber: "u-807d8407-e4dc-5c00-84c1-84b3d151cf9d"
    calledNumber: "st-48478422-174f-5a15-928f-72e5702541ce"
    traceId: "3d6a5d8e931fed28eb6a8f26d824d740"
    options: {
      "actionHook": "/actions/hooks",
      "input": [
        "digits",
        "speech"
      ],
      "interDigitTimeout": 2,
      "minDigits": 1,
      "finishOnKey": "#",
      "numDigits": 12,
      "say": {
        "text": [
          "Say something, I will echo that"
        ]
      },
      "bargein": false,
      "listenDuringPrompt": false,
      "timeout": 10,
      "dtmfBargein": false,
      "recognizer": {
        "hints": [],
        "altLanguages": []
      }
    }
INFO [05:59:41.747] (1028738): stt: nuance , label: nuance-cloud  
    callId: "cd20ec79-9e6c-123d-7d9a-0e2ecbcba261"
    callSid: "8a347f80-8306-40f5-b689-c0a31a5351a0"
    accountSid: "3978e7ef-e014-4a9e-9184-ff24a19d9fad"
    callingNumber: "u-807d8407-e4dc-5c00-84c1-84b3d151cf9d"
    calledNumber: "st-48478422-174f-5a15-928f-72e5702541ce"
    traceId: "3d6a5d8e931fed28eb6a8f26d824d740"
ERROR [05:59:41.789] (1028738): Error executing task  #1:6: gather
    callId: "cd20ec79-9e6c-123d-7d9a-0e2ecbcba261"
    callSid: "8a347f80-8306-40f5-b689-c0a31a5351a0"
    accountSid: "3978e7ef-e014-4a9e-9184-ff24a19d9fad"
    callingNumber: "u-807d8407-e4dc-5c00-84c1-84b3d151cf9d"
    calledNumber: "st-48478422-174f-5a15-928f-72e5702541ce"
    traceId: "3d6a5d8e931fed28eb6a8f26d824d740"
    err: {
      "type": "Error",
      "message": "",
      "stack":
          Error
              at getNuanceAccessToken (/home/admin/apps/savgw-feature-server/node_modules/@jambonz/speech-utils/lib/get-nuance-access-token.js:35:19)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async TaskGather._initSpeechCredentials (/home/admin/apps/savgw-feature-server/lib/tasks/stt-task.js:187:47)
              at async TaskGather.exec (/home/admin/apps/savgw-feature-server/lib/tasks/stt-task.js:123:31)
              at async TaskGather.exec (/home/admin/apps/savgw-feature-server/lib/tasks/gather.js:126:5)
              at async InboundCallSession.exec (/home/admin/apps/savgw-feature-server/lib/session/call-session.js:984:11)
      "statusCode": 401
    }

**Comment by vdharashive** [comment]
this is not required
