### ISSUE TITLE
Non Success SIP Response causes error

### ISSUE THREAD

**Issue by ajukes** [jambonz/jambonz-feature-server#8]
When remote endpoint responds with 503 for example, logs show error and returns 500 Server error to application

```
WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
TypeError: Cannot read property 'updateCallStatus' of undefined
    at new CallSession (/home/deploy/jambonz-feature-server/lib/session/call-session.js:21:50)
    at new RestCallSession (/home/deploy/jambonz-feature-server/lib/session/rest-call-session.js:7:5)
    at cbRequest (/home/deploy/jambonz-feature-server/lib/http-routes/api/create-call.js:124:16)
    at Object._app.request [as callback] (/home/deploy/jambonz-feature-server/node_modules/drachtio-srf/lib/srf.js:400:9)
    at DrachtioAgent.obj.pendingRequests.set (/home/deploy/jambonz-feature-server/node_modules/drachtio-srf/lib/drachtio-agent.js:310:16)
    at DrachtioAgent._onMsg (/home/deploy/jambonz-feature-server/node_modules/drachtio-srf/lib/drachtio-agent.js:717:11)
    at WireProtocol.emit (events.js:198:13)
    at WireProtocol.processMessageBuffer (/home/deploy/jambonz-feature-server/node_modules/drachtio-srf/lib/wire-protocol.js:270:12)
    at WireProtocol._onData (/home/deploy/jambonz-feature-server/node_modules/drachtio-srf/lib/wire-protocol.js:304:14)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:264:13)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

```

**Comment by davehorton** [comment]
fixed?
