### ISSUE TITLE
actionhook delay error 

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-feature-server#916]
Saw this error on jambonz.cloud

```
7|jambonz-feature-server  | {"level":20,"time":1727303381839,"pid":677345,"hostname":"ip-172-20-10-61","callId":"6a3bcc29-f630-123d-598a-0e9252b57157","callSid":"0f6ff7b7-76eb-4e58-85df-4671714789e8","accountSid":"673427f1-49a4-4e93-933d-c6327c04dddc","callingNumber":"2199001167","calledNumber":"2019401575","traceId":"90b7d82a030abc7bbcf9be5e79d5e18c","evt":{"file":"https://precious-idea-sjfsx.ampt.app/public/fast-pace-Typing-on-mechanical-keyboard-1-www.FesliyanStudios.com.mp3"},"msg":"got playback-start"}
7|jambonz-feature-server  | TypeError: Cannot read properties of null (reading 'api')
7|jambonz-feature-server  |     at Endpoint.<anonymous> (/home/admin/apps/jambonz-feature-server/lib/utils/action-hook-delay.js:140:17)
7|jambonz-feature-server  |     at Object.onceWrapper (node:events:634:26)
7|jambonz-feature-server  |     at Endpoint.emit (node:events:519:28)
7|jambonz-feature-server  |     at Endpoint._onPlaybackStart (/home/admin/apps/jambonz-feature-server/node_modules/drachtio-fsmrf/lib/endpoint.js:1696:15)
7|jambonz-feature-server  |     at EventEmitter.emit (/home/admin/apps/jambonz-feature-server/node_modules/eventemitter2/lib/eventemitter2.js:1047:22)
7|jambonz-feature-server  |     at Connection._onEvent (/home/admin/apps/jambonz-feature-server/node_modules/drachtio-modesl/lib/esl/Connection.js:828:10)
7|jambonz-feature-server  |     at EventEmitter.emit (/home/admin/apps/jambonz-feature-server/node_modules/eventemitter2/lib/eventemitter2.js:1047:22)
7|jambonz-feature-server  |     at Parser._parseEvent (/home/admin/apps/jambonz-feature-server/node_modules/drachtio-modesl/lib/esl/Parser.js:208:10)
7|jambonz-feature-server  |     at Parser._parseBody (/home/admin/apps/jambonz-feature-server/node_modules/drachtio-modesl/lib/esl/Parser.js:100:10)
7|jambonz-feature-server  |     at Parser._parseHeaders (/home/admin/apps/jambonz-feature-server/node_modules/drachtio-modesl/lib/esl/Parser.js:76:37)
7|jambonz-feature-server  | {"level":30,"time":1727303381839,"pid":677345,"hostname":"ip-172-20-10-61","callId":"6a3bcc29-f630-123d-598a-0e9252b57157","callSid":"0f6ff7b7-76eb-4e58-85df-4671714789e8","accountSid":"673427f1-49a4-4e93-933d-c6327c04dddc","callingNumber":"2199001167","calledNumber":"2019401575","traceId":"90b7d82a030abc7bbcf9be5e79d5e18c","evt":{"file":"https://precious-idea-sjfsx.ampt.app/public/fast-pace-Typing-on-mechanical-keyboard-1-www.FesliyanStudios.com.mp3"},"msg":"ActionHookDelayProcessor#_onNoResponseTimer: killing audio immediately"}
PM2                       | App [jambonz-feature-server:7] exited with code [1] via signal [SIGINT]
PM2                       | App [jambonz-feature-server:7] starting in -fork mode-
PM2                       | App [jambonz-feature-server:7] online
7|jambonz-feature-server  | {"level":20,"time":1727303382207,"pid":677978,"hostname":"ip-172-20-10-61","msg":"installing srf locals"}
```

**Comment by davehorton** [comment]
code is
```
  _onNoResponseTimer() {
    this.logger.debug('ActionHookDelayProcessor#_onNoResponseTimer');
    this._noResponseTimer = null;

    /* get the next play or say action */
    const verb = this.actions[this._retryCount % this.actions.length];

    const t = normalizeJambones(this.logger, [verb]);
    this.logger.debug({verb}, 'ActionHookDelayProcessor#_onNoResponseTimer: starting action');
    try {
      this._taskInProgress = makeTask(this.logger, t[0]);
      this._taskInProgress.disableTracing = true;
      this._taskInProgress.exec(this.cs, {ep: this.ep});
    } catch (err) {
      this.logger.info(err, 'ActionHookDelayProcessor#_onNoResponseTimer: error starting action');
      this._taskInProgress = null;
      return;
    }

    this.ep.once('playback-start', (evt) => {
      this.logger.debug({evt}, 'got playback-start');
      if (!this._active) {
        this.logger.info({evt}, 'ActionHookDelayProcessor#_onNoResponseTimer: killing audio immediately');
        this.ep.api('uuid_break', this.ep.uuid)
          .catch((err) => this.logger.info(err,
            'ActionHookDelayProcessor#_onNoResponseTimer Error killing audio'));
      }
    });
```
where `  this.ep.api('uuid_break', this.ep.uuid)` was the culprit
