### ISSUE TITLE
Issue: Feature Server restarts on sip-refer notify webhook error

### ISSUE THREAD

**Issue by sammachin** [jambonz/jambonz-feature-server#996]
I've identified a scenario where the customers application crashes mid call and then the feature-server sends a webhook for a sip_refer. This results in UND_ERR_CLOSED from undici as it see the HTTP connection to the application as closed but this error when surfaced up to jambonz is not handled, thus the application quits.

Log entries showing the error and the restart
```
{"timestamp":"2024-12-09T09:43:09.317Z","errorGroups":[{"id":"CPiaqfXUoKuAOA"}],"log":{"msg":"web callback returned unexpected error","callId":"ca745f95-30b4-123e-90b8-42010a9c0004","url":"/jambonz-status","callSid":"b424f454-2ca9-4855-a804-d91a775e531c","level":50,"calledNumber":"9000","accountSid":"6fb344fd-f3b9-463a-b3bb-3ba8561590cd","baseUrl":"http://bot-router.apps",
	"err":
	{"message":"The client is closed",
		"type":"ClientClosedError",
		"code":"UND_ERR_CLOSED",
		"stack":"
			ClientClosedError: The client is closed\n    
				at Client.dispatch (/opt/app/node_modules/undici/lib/dispatcher/dispatcher-base.js:174:15)\n    
				at Client.request (/opt/app/node_modules/undici/lib/api/api-request.js:203:10)\n    
				at /opt/app/node_modules/undici/lib/api/api-request.js:196:15\n    
				at new Promise (<anonymous>)\n    
				at Client.request (/opt/app/node_modules/undici/lib/api/api-request.js:195:12)\n    
				at HttpRequestor.request (/opt/app/lib/utils/http-requestor.js:183:24)\n    
				at TaskSipRefer.performAction (/opt/app/lib/tasks/task.js:168:46)\n    
				at TaskSipRefer._handleNotify (/opt/app/lib/tasks/sip_refer.js:97:22)\n    
				at process.processTicksAndRejections 
				(node:internal/process/task_queues:95:5)",
		"name":"ClientClosedError"},
		"pid":1,
		"callingNumber":"[REDACTED]",
		"traceId":"12066ae4d6ef626b4339250f6a69c3ff",
		"hostname":"feature-server-6f8c7d57f9-zcbv8"
}}

	node:internal/process/promises:288
		triggerUncaughtException(err, true /* fromPromise */);
{"timestamp":"2024-12-09T09:43:09.324413162Z","severity":"ERROR","log":{}}
	ClientClosedError: The client is closed\n
	    at Client.dispatch (/opt/app/node_modules/undici/lib/dispatcher/dispatcher-base.js:174:15)\n
		at Client.request (/opt/app/node_modules/undici/lib/api/api-request.js:203:10)\n
		at /opt/app/node_modules/undici/lib/api/api-request.js:196:15\n
		at new Promise (<anonymous>)\n
		at Client.request (/opt/app/node_modules/undici/lib/api/api-request.js:195:12)\n
		at HttpRequestor.request (/opt/app/lib/utils/http-requestor.js:183:24)\n
		at TaskSipRefer.performAction (/opt/app/lib/tasks/task.js:168:46)\n    
		at TaskSipRefer._handleNotify (/opt/app/lib/tasks/sip_refer.js:97:22)\n    ///https://github.com/jambonz/jambonz-feature-server/blob/54cc76606b76484e9792dbb47bd3625fe860b95d/lib/tasks/sip_refer.js#L97 - Unhandled error
		at process.processTicksAndRejections (node:internal/process/task_queues:95:5
	  code: 'UND_ERR_CLOSED'

{"textPayload":"}","timestamp":"2024-12-09T09:43:09.324487410Z","severity":"ERROR"}
{"timestamp":"2024-12-09T09:43:09.324512842Z","severity":"ERROR","log":{}}
{"textPayload":"Node.js v18.15.0","timestamp":"2024-12-09T09:43:09.324516668Z","severity":"ERROR"}
{"timestamp":"2024-12-09T09:43:10.692Z","log":{"level":30,"msg":"SBC inventory","sbcs":["sbc-sip:5060"],"pid":1,"hostname":"feature-server-6f8c7d57f9-zcbv8"}}
{"timestamp":"2024-12-09T09:43:10.703Z","log":{"level":30,"msg":"sending stats to telegraf.monitoring","pid":1,"hostname":"feature-server-6f8c7d57f9-zcbv8"}}
{"timestamp":"2024-12-09T09:43:10.704Z","log":{"fsInventory":[{"secret":"JambonzR0ck$","address":"127.0.0.1","port":"8021"}],"hostname":"feature-server-6f8c7d57f9-zcbv8","pid":1,"msg":"freeswitch inventory","level":30}}
{"timestamp":"2024-12-09T09:43:13.478Z","log":{"hostname":"feature-server-6f8c7d57f9-zcbv8","msg":"listening for HTTP requests on port 3000, serviceUrl is http://10.36.9.124:3000","level":30,"pid":1}}
{"timestamp":"2024-12-09T09:43:13.579Z","log":{"msg":"disabling OPTIONS pings since we are running as a kubernetes service","pid":1,"hostname":"feature-server-6f8c7d57f9-zcbv8","level":30}}
{"timestamp":"2024-12-09T09:43:13.599Z","log":{"hostname":"feature-server-6f8c7d57f9-zcbv8","level":30,"msg":"connected to drachtio listening on udp/127.0.0.1:5060,udp/10.36.9.124:5060, local sip address is 10.36.9.124:5060","pid":1}}
{"timestamp":"2024-12-09T09:43:13.628Z","log":{"msg":"connected to freeswitch at 127.0.0.1","pid":1,"hostname":"feature-server-6f8c7d57f9-zcbv8","level":30}}
```

**Comment by sammachin** [comment]
I've identified that the await performAction at https://github.com/jambonz/jambonz-feature-server/blob/main/lib/tasks/sip_refer.js#L97 would not catch an error thrown up from here https://github.com/jambonz/jambonz-feature-server/blob/54cc76606b76484e9792dbb47bd3625fe860b95d/lib/tasks/task.js#L199

However I am unable to re-create this scenario with a test application, I've tried closing the socket, setting the keep-alive then killing the applicaiton and various other methods but these result in different errors mostl UND_ERR_SOCKET or ECONNREFUSED.

**Comment by sammachin** [comment]
Will PR a fix to catch the error in sip_refer

**Comment by davehorton** [comment]
ok I think its critical we recreate though before merging a fix

**Comment by davehorton** [comment]
agree that looks like the right solution, though.  Also, I wonder if undici exposes a method to tell us whether the connection is in this "client closed" state?

**Comment by sammachin** [comment]
The client app that causes these crashes uses http/2 which explains why I couldn't trigger the undici error with a basic express app.

Will look at creating an http/2 application that closes the connection

**Comment by sammachin** [comment]
http/2 was a red herring
